name = "my-product"
main = "src/index.ts"
compatibility_date = "2025-01-14"

# compatibility_flags = [ "nodejs_compat" ]

[vars]
SECRET = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "my-product"
database_id = "9f9111e7-079c-4375-a2f2-c20cae3331d7"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1